TENSORS AND OPERATION (DEEP DIVE)

1 MULTIDIMENSIONAL TENSORS

0D- Scalar - torch.tensor(5)
1D - vector - torch.tensor([1,2,3])
2D -Matrix  - torch.tensor([1,2],[3,4])
3D -Stack of matrices - torch.tensor([[[1,2],[3,4],[5,6],[7,8]]])

In [32]:
import torch

In [33]:
x=torch.tensor([1.0,2.0,3.0])
y=torch.tensor([2.0,3.0,4.0])

z=x+y
z=x*y

In [34]:
z

tensor([ 2.,  6., 12.])

In [35]:
a=torch.tensor([[1,2],[4,5]])
b=torch.tensor([[7,8],[10,11]])
c=torch.matmul(a,b)

print(c)

tensor([[27, 30],
        [78, 87]])


In [36]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
y=x**2+2*x+1
y.sum().backward()
print(x.grad)

tensor([4., 6., 8.])


2-LAYER LINEAR NETWORK


y=2x^2+3x+1

In [37]:
import torch
import torch.nn as nn
import torch.optim as optim

In [38]:
X=torch.tensor([[1.0],[2.0],[3.0],[4.0]])
Y=torch.tensor([[6.0],[15.0],[28.0],[45.0]])

In [39]:
class TwoLayerNN(nn.Module):
    def __init__(self):
        super(TwoLayerNN,self).__init__()
        self.hidden=nn.Linear(1,5)
        self.relu=nn.ReLU()
        self.output=nn.Linear(5,1)
    def forward(self,x):
        x=self.hidden(x)
        x=self.relu(x)
        x=self.output(x)
        return x    

In [40]:
model=TwoLayerNN()

In [47]:
loss_fn=nn.MSELoss()
optimizer=optim.SGD(params=model.parameters(),lr=0.00001)

In [48]:
epochs=2000

for epoch in range(epochs):
    model.train()
    y_pred=model(X)
    
    loss=loss_fn(y_pred,Y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1)%200 == 0:
        print(f"Epoch :{epoch+1}, | Loss : {loss.item()}")



          




Epoch :200, | Loss : 3.1416430473327637
Epoch :400, | Loss : 3.1368491649627686
Epoch :600, | Loss : 3.1320571899414062
Epoch :800, | Loss : 3.1272714138031006
Epoch :1000, | Loss : 3.1224892139434814
Epoch :1200, | Loss : 3.11771297454834
Epoch :1400, | Loss : 3.1129403114318848
Epoch :1600, | Loss : 3.108173370361328
Epoch :1800, | Loss : 3.103410243988037
Epoch :2000, | Loss : 3.0986521244049072


In [49]:
with torch.no_grad():
    prediction=model(X)

    print(prediction)

tensor([[ 9.1144],
        [14.1829],
        [29.2897],
        [44.3965]])
